-- MySQL Script generated by MySQL Workbench
-- sex 10 jul 2020 04:00:26 WEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crypto-exchange
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crypto-exchange
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crypto-exchange` DEFAULT CHARACTER SET utf8mb4 ;
USE `crypto-exchange` ;

-- -----------------------------------------------------
-- Table `crypto-exchange`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crypto-exchange`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(254) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `verified` TINYINT NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `token` VARCHAR(128) NOT NULL,
  `timestamp` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `crypto-exchange`.`wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crypto-exchange`.`wallet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `currency` VARCHAR(10) NOT NULL,
  `balance` DECIMAL(20,8) NOT NULL,
  `usd` DECIMAL(15,4) NOT NULL,
  `eur` DECIMAL(15,4) NOT NULL,
  `value` DECIMAL(20,8) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_wallet_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `crypto-exchange`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `crypto-exchange`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crypto-exchange`.`staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `level` TINYINT NOT NULL,
  `active` TINYINT NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `token` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `crypto-exchange`.`store_wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crypto-exchange`.`store_wallet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `currency` VARCHAR(10) NOT NULL,
  `balance` DECIMAL(20,8) NOT NULL,
  `fee` DECIMAL(5,2) NOT NULL,
  `usd` DECIMAL(15,4) NOT NULL,
  `eur` DECIMAL(15,4) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `currency_UNIQUE` (`currency` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `crypto-exchange`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crypto-exchange`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `body` LONGTEXT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
